from typing import Protocol

from app.domain.bookings.entity import Bookings


class IBookingRepository(Protocol):
    async def create(self, domain: Bookings) -> Bookings: ...

    async def find_all(self, limit: int, offset: int) -> list[Bookings] | None: ...

    async def filter_by(self, **parameters) -> list[Bookings] | None: ...

    async def update(self, data: dict, id: int) -> Bookings: ...

    async def delete(self, **parameters) -> Bookings: ...

    async def is_exist(self, domain: Bookings) -> bool: ...
