from typing import Protocol, Any

from app.domain.hotels.entity import Hotels


class IHotelRepository(Protocol):
    async def create(self, data: dict) -> Hotels: ...

    async def find_all(self, limit: int, offset: int) -> list[Hotels] | None: ...

    async def filter_by(self, **parameters) -> list[Hotels] | None: ...

    async def update(self, data: dict, id: int) -> Hotels: ...

    async def delete(self, **parameters) -> Hotels: ...
