from typing import Protocol

from app.domain.rooms.entity import Rooms


class IRoomRepository(Protocol):
    async def create(self, data: dict) -> Rooms: ...

    async def find_all(self, hotel_id: int, limit: int, offset: int) -> list[Rooms] | None: ...

    async def filter_by(self, **parameters) -> list[Rooms] | None: ...

    async def update(self, data: dict, id: int) -> Rooms: ...

    async def delete(self, **parameters) -> Rooms: ...